// <auto-generated />
using CadastroEstabelecimento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroEstabelecimento.data
{
    [DbContext(typeof(CadastroEstabelecimentoContext))]
    [Migration("20210228021838_Initial")]
    partial class Initial : InitialBase
    {
    }
}
